- name: "Install nfs-utils"
  ansible.builtin.dnf:
    name: nfs-utils
    state: latest
  become: true

- name: "Start rpcbind"
  ansible.builtin.systemd:
    name: rpcbind
    state: started
    enabled: true
  become: true

- name: "Mount home directory"
  ansible.posix.mount:
    name: "{{ common_nfshome_dest }}/{{ item }}"
    src: "{{ common_nfshome_src_host }}:{{ common_nfshome_src_dir }}/{{ item }}"
    fstype: nfs
    state: mounted
  become: true
  loop: "{{ common_nfshome_users }}"

- name: Install autofs
  ansible.builtin.dnf:
    name: autofs
    state: latest
  become: true

- name: Copy home.conf
  ansible.builtin.template:
    src: shun.auto.home.conf
    dest: /etc/auto.master.d/home.autofs
    owner: root
    group: root
    mode: "0644"
  become: true

- name: "Copy auto.home"
  ansible.builtin.template:
    src: shun.auto.home
    dest: /etc/auto.home
    owner: root
    group: root
    mode: "0644"
  become: true

- name: "Start autofs"
  ansible.builtin.systemd:
    name: autofs
    state: restarted
    enabled: true
  become: true
