---
# tasks file for base

- include: common/main.yml
- include: dotfiles/main.yml
  when: shun_base_dotfiles_install
- include: nfshome/main.yml
  when: shun_base_nfshome_install
- include: ldapauth/main.yml
  when: shun_base_ldapauth_install
