---
# tasks file for base

- include: centos.yml
  when:
    - ansible_distribution == "CentOS"

- include: ubuntu16.yml
  when:
   - ansible_distribution == "Ubuntu"
   - ansible_distribution_major_version == "16"

- include: ubuntu18.yml
  when:
   - ansible_distribution == "Ubuntu"
   - ansible_distribution_major_version == "18"
