---
# tasks file for base

- name: "Include common"
  ansible.builtin.include_tasks: common/main.yml
- name: "Include dotfiles"
  ansible.builtin.include_tasks: dotfiles/main.yml
  when: shun_base_dotfiles_install
- name: "Include nfshome"
  ansible.builtin.include_tasks: nfshome/main.yml
  when: shun_base_nfshome_install
- name: "Include ldapauth"
  ansible.builtin.include_tasks: ldapauth/main.yml
  when: shun_base_ldapauth_install
