---
# defaults file for base

common_username: shun
common_loginshell: /bin/bash

common_default_packages:
  - git
  - vim
  - zsh
  - openssl
  - curl
  - tar
  - make
  - zip
  - unzip
  - python3
  - python3-pip

common_selinux: disabled

common_ntp_servers:
  - 0.jp.pool.ntp.org
  - 1.jp.pool.ntp.org
  - 2.jp.pool.ntp.org
  - 3.jp.pool.ntp.org

common_dotfiles_install: true
common_dotfiles_repo: https://github.com/mypaceshun/dotfiles.git
common_dotfiles_dest: dotfiles
common_dotfiles_branch: master
common_dotfiles_setup_shell: ./setup.sh

common_nfshome_install: false
# common_nfshome_dest: "/home/{{ common_username }}"
# common_nfshome_src_host: 192.168.121.1
# common_nfshome_src_dir: /home-vagrant

common_autofs_src_host: 192.168.121.1
common_autofs_src_dir: /home-vagrant

common_ldapauth_install: true
common_ldapauth_uris: ldap://localhost
common_ldapauth_search_base: dc=example,dc=com
common_ldapauth_bind_dn: cn=master,dc=example,dc=com
common_ldapauth_bind_pass: pass
common_ldapauth_sssd_domain: shun.local
