---

- debug:
    msg: "Running shun base role for [{{ansible_distribution}}{{ansible_distribution_major_version}}]"

- name: change timezone to Asia/Tokyo
  file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=true
  become: true

- name: Install chrony
  yum:
    name: chrony
    state: latest
  become: true

- name: Copy chrony.conf
  template:
    src: shun.chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: "Restart chronyd"

- name: start chronyd
  service:
    name: chronyd
    state: started
    enabled: true
  become: true

- name: "yum install default packages"
  yum:
    name: "{{ shun_base_default_packages }}"
    state: latest
  become: true

- name: "install glibc"
  yum:
    name: glibc
    name: glibc-common
    state: latest
  become: true
  when: ansible_distribution_major_version == "7"

- name: "install langpacks-ja"
  yum:
    name: 
    - langpacks-ja
    - glibc-langpack-ja
    state: latest
  become: true
  when: ansible_distribution_major_version == "8"

- name: "locale create ja_JP.UTF-8"
  shell: "localedef -f UTF-8 -i ja_JP ja_JP.UTF-8"
  args:
    executable: /bin/bash
  become: true 
  when: ansible_distribution_major_version == "7"

- name: "Disabled SELinux"
  selinux:
    state: disabled
  become: true

- name: "Change loginshell"
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items:
    - "{{ ansible_env.USER }}"
    - root
  become: true

- name: "Deploy /etc/hosts"
  template:
    src: shun.hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  become: true
  when: shun_base_hosts_install

- name: "sshd PasswordAuthentication yes"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication no'
    line: 'PasswordAuthentication yes'
  become: true

- name: "restart sshd"
  service:
    name: sshd
    state: restarted
    enabled: true
  become: true
