---

- name: Change timezone to Asia/Tokyo
  ansible.builtin.file:
    src: /usr/share/zoneinfo/Asia/Tokyo
    dest: /etc/localtime
    state: link
    force: true
  become: true

- name: Install chrony
  ansible.builtin.yum:
    name: chrony
    state: latest
  become: true

- name: Copy chrony.conf
  ansible.builtin.template:
    src: shun.chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: "Restart chronyd"

- name: Start chronyd
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true
  become: true

- name: "Yum install default packages"
  ansible.builtin.yum:
    name: "{{ shun_base_default_packages }}"
    state: latest
  become: true

- name: "Install glibc"
  ansible.builtin.yum:
    name:
      - glibc
      - glibc-common
    state: latest
  become: true
  when: ansible_distribution_major_version == "7"

- name: "Install langpacks-ja"
  ansible.builtin.yum:
    name:
      - langpacks-ja
      - glibc-langpack-ja
    state: latest
  become: true
  when: ansible_distribution_major_version >= "8"

- name: "Locale create ja_JP.UTF-8"
  ansible.builtin.shell: "localedef -f UTF-8 -i ja_JP ja_JP.UTF-8"
  args:
    executable: /bin/bash
  become: true
  when: ansible_distribution_major_version == "7"

- name: "SELinux {{ shun_base_selinux }}"
  ansible.posix.selinux:
    state: "{{ shun_base_selinux }}"
  become: true

- name: "Change loginshell"
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items:
    - "{{ ansible_env.USER }}"
    - root
  become: true

- name: "Deploy /etc/hosts"
  ansible.builtin.template:
    src: shun.hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"
  become: true
  when: shun_base_hosts_install

- name: "Sshd PasswordAuthentication yes"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication no'
    line: 'PasswordAuthentication yes'
  become: true

- name: "Restart sshd"
  ansible.builtin.service:
    name: sshd
    state: restarted
    enabled: true
  become: true
