---
# handlers file for base

- name: "Restart chronyd"
  service:
    name: chronyd
    state: restarted
    enabled: true
  become: true

- name: "Restart sssd"
  service:
    name: sssd
    state: restarted
    enabled: true
  become: true

