---

- name: "Git clone dotfiles"
  ansible.builtin.git:
    repo: "{{ shun_base_dotfiles_repo }}"
    dest: "{{ shun_base_dotfiles_dest }}"
    version: "{{ shun_base_dotfiles_branch }}"

- name: "Dotfiles setup"
  ansible.builtin.shell: "{{ shun_base_dotfiles_setup_shell }}"
  args:
    chdir: "{{ shun_base_dotfiles_dest }}"
    executable: /bin/bash
  register: result_setup_dotfiles
  changed_when: result_setup_dotfiles.rc == 0

- name: "PlugInstall"
  ansible.builtin.shell: |
    set -o pipefail
    TEMPFILE=`mktemp`
    echo ':PlugInstall\n:qa!' > ${TMPFILE}
    vim -s ${TMPFILE}
  args:
    executable: /bin/bash
  register: result
  changed_when: result.return_code == 0

- name: "Git clone dotfiles for root"
  ansible.builtin.git:
    repo: "{{ shun_base_dotfiles_repo }}"
    dest: "/root/{{ shun_base_dotfiles_dest }}"
    version: "{{ shun_base_dotfiles_branch }}"
  become: true

- name: "Dotfiles setup for root"
  ansible.builtin.shell: "{{ shun_base_dotfiles_setup_shell }}"
  args:
    chdir: "/root/{{ shun_base_dotfiles_dest }}"
    executable: /bin/bash
  register: result_setup_dotfiles
  changed_when: result_setup_dotfiles.rc == 0
  become: true

- name: "PlugInstall"
  ansible.builtin.shell: |
    TEMPFILE=`mktemp`
    echo ':PlugInstall\n:qa!' > ${TMPFILE}
    vim -s ${TMPFILE}
  args:
    executable: /bin/bash
  register: result
  changed_when: result.rc == 0
  become: true
