---

- name: "Install sssd"
  ansible.builtin.yum:
    name:
      - sssd
      - sssd-tools
      - sssd-dbus
      - authconfig
      - oddjob-mkhomedir
    state: latest
  become: true

- name: "Copy sssd.conf"
  ansible.builtin.template:
    src: shun.sssd.conf
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: "600"
  become: true
  notify: "Restart sssd"

- name: "Set ldappassword"
  ansible.builtin.shell: |
    set -o pipefail
    echo -n '{{ shun_base_ldapauth_bind_pass }}' | sss_obfuscate -s -d {{ shun_base_ldapauth_sssd_domain }}
  args:
    executable: /bin/bash
  register: result_ldappassword
  changed_when: result_ldappassword.rc == 0
  no_log: true
  become: true
  notify: "Restart sssd"

- name: "Exec authconfig"
  ansible.builtin.shell: authconfig --disableldap --disableldapauth --enablesssd --enablesssdauth --enablemkhomedir --update
  args:
    executable: /bin/bash
  register: result_authconfig
  changed_when: result_authconfig.rc == 0
  become: true
  notify: "Restart sssd"

- name: "Rewrite nsswitch.conf"
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^sudoers:'
    insertafter: EOF
    line: 'sudoers:    files sss'
  become: true

- name: "Start sssd"
  ansible.builtin.service:
    name: sssd
    state: started
    enabled: true
  become: true

- name: "Start oddjobd"
  ansible.builtin.service:
    name: oddjobd
    state: started
    enabled: true
  become: true
