- name: "Include ldapauth centos7"
  ansible.builtin.include_tasks: centos7.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: "Include ldapauth centos8"
  ansible.builtin.include_tasks: centos8.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"

- name: "Include ldapauth centos8"
  ansible.builtin.include_tasks: centos8.yml
  when:
    - ansible_distribution == "AlmaLinux"
    - ansible_distribution_major_version == "8"

- name: "Include ldapauth centos8"
  ansible.builtin.include_tasks: centos8.yml
  when:
    - ansible_distribution == "AlmaLinux"
    - ansible_distribution_major_version == "9"
