- include: centos7.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- include: centos8.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"

- include: centos8.yml
  when:
    - ansible_distribution == "AlmaLinux"
    - ansible_distribution_major_version == "8"

- include: centos8.yml
  when:
    - ansible_distribution == "AlmaLinux"
    - ansible_distribution_major_version == "9"
