- name: "Install nfs-utils"
  yum:
    name: nfs-utils
    state: latest
  become: true

- name: "Start rpcbind"
  service:
    name: rpcbind
    state: started
    enabled: true
  become: true

- name: "Mount home directory"
  mount:
    name: "{{ shun_base_nfshome_dest }}"
    src: "{{ shun_base_nfshome_src_host }}:{{ shun_base_nfshome_src_dir }}"
    fstype: nfs
    state: mounted
  become: true
